language: node_js

node_js:
  - 0.10

env:
  - secure: Dt1/TndktpPqZlPeqCLfa6WMV66hYgGroNOVs6Kr9XLop3DACutHh9ujk3cRs/qybzEG6rMXj8bZoRkl9Zp/EoYCkWE4RM2eEg28M02s34jhK28NM5Jxcj5znpRvmxxemprkYbRwl3hCWcw3TsFp0dDWHw1/ZhkN8tTs8sGpzxU=

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
  - npm run-script build

after_success:
  - npm install codeclimate-test-reporter
  - ./node_modules/.bin/istanbul cover --report lcovonly ./node_modules/.bin/_mocha -- ./test/test.js
  - cat ./coverage/lcov.info | ./node_modules/.bin/codeclimate
