language: node_js

node_js:
  - 0.10

env:
  global:
    # CODECLIMATE_REPO_TOKEN
    - secure: UR3Fth+3x7k4zAiYUe/GNM19HhaboA/v1XhHC9IO239beIzZAwqbIi0IKpt8rNWXxnoSS8oVlz7ABoFy3iilXDNGE2t6r53mDllWT8SlcBNMgDp+A56VzClVGodJatTkrPTWmu8dGsa9YaIVOBbAvytalEgd3ib4rk0MQl/y1zs=

before_script:
  - npm install -g eslint jscs
  - npm run-script build
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

after_success:
  - npm install codeclimate-test-reporter
  - ./node_modules/.bin/istanbul cover --report lcovonly ./node_modules/.bin/_mocha -- --reporter=dot ./test/test.js
  - cat ./coverage/lcov.info | ./node_modules/.bin/codeclimate

deploy:
  - provider: npm
    email: rs@ruslansagitov.name
    api_key:
      secure: aBHJltDzWk/QIsMk/FJUWF4glByXAXIizh+bbB1f3d5As6c4u6pJvCUxQBkrQWmV71Nf/MfBVvhuqHKH+ZifGzIpWKAtdO5yGzaVdxRUhNU7GEfxX0HQkkKIjUe0pOz8RkQXe7Vln8UV5eLGyeHLXs5HyN2VnFSOQKrw4dh3DPk=
    on:
      tags: true
      repo: ruslansagitov/loud
