language: node_js

node_js:
  - 4

sudo: false

env:
  global:
    # CODECLIMATE_REPO_TOKEN
    - secure: UR3Fth+3x7k4zAiYUe/GNM19HhaboA/v1XhHC9IO239beIzZAwqbIi0IKpt8rNWXxnoSS8oVlz7ABoFy3iilXDNGE2t6r53mDllWT8SlcBNMgDp+A56VzClVGodJatTkrPTWmu8dGsa9YaIVOBbAvytalEgd3ib4rk0MQl/y1zs=
    # COVERALLS_REPO_TOKEN
    - secure: RH5Gn2xCyZ8wlN9TRt0Sdn6oQuonjpOVqdIC3BRNhAK1r5tUCZuhAj8KSN6IjAaajXmN5/6sw1FpRFy29SSqs98bIuMseqqN7Q7XVQrJ7H9CM3SsJr9lbBWUbpH4l1wqTb+WLP2rC0oNXbA0JcU46o6Wx7NdiTKPa77kYmf1Ey0=
    # SAUCE_USERNAME
    - secure: cRiggKCu0Y7SW1qkOt3JzaOcZVgZ8sJcJ30kTCRUhHCP9cIUFhqT61NYAtYJ9yLVPdystKzyphO7YoXmVYhuOdn/qFvGGFOCekkSG2VlQZU8q5cwA7QxMp+YYU+MBq+C7xEerzOF+wo7YYfv0w2VqcpfJgFb4eha13vz/HueqK4=
    # SAUCE_ACCESS_KEY
    - secure: Besc0YZAzEyo0o+BJx+h8d5NqTanQr0jaQbfop5HUCfbrmakzQrxbdXdmW0cZUr2f12jYN/k2FXo6uZ19tPCLoWF9aGlIDLMX9yRJdiVWQU8voPVpwY+rsVG5Io4UOmrEmeyP0cwKfuzkaq7dJZe9Zd/DKz3ND5761HkJJEgdF4=

cache:
  directories:
    - node_modules

before_install:
  - npm install --global npm@^3.5.3
  - npm install --global eslint@^1.10.3 jscs@^2.8.0 write-good@^0.9.1 nsp@^2.2.0
  - npm install --global karma-cli@^0.1.2

before_script:
  - npm install karma-firefox-launcher@^0.1.7 karma-phantomjs-launcher@^0.2.2 phantomjs@^1.9.19
  - test -n "$SAUCE_ACCESS_KEY" && npm install karma-sauce-launcher@^0.3.0
  - export KARMA_BROWSERS=Firefox,PhantomJS
  - mkdir build
  - npm run-script build
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

after_success:
  - npm install codeclimate-test-reporter@^0.3.0 coveralls@^2.11.6
  - npm run-script build-coverage
  - KARMA_COVERAGE=lcovonly KARMA_BROWSERS=Firefox SAUCE_ACCESS_KEY= npm run-script karma-test
  - cat ./coverage/*/lcov.info | ./node_modules/.bin/codeclimate-test-reporter
  - cat ./coverage/*/lcov.info | ./node_modules/.bin/coveralls

deploy:
  - provider: npm
    email: rs@ruslansagitov.name
    api_key:
      secure: ECZLkx5BEvOmpslzN5I6sKO++W0fB8upneBfvU4qkIEsaeYY5mOdNW81reUcC6ZIrGzKQ2hVAm06e0+flbHN9x1iyw3IZv+GWOUo2RdpdRQZLXWqKayXxCVx90lQNk5GaUjTOgrlwpymh+j7Lpw6CI9WsvWbGtkJCQpVRJ8zz+0=
    on:
      all_branches: true
      tags: true
      repo: ruslansagitov/loud
