version: '{build}'

environment:
  nodejs_version: 12

matrix:
  fast_finish: true

cache:
  - node_modules -> package.json
  - '%APPDATA%\npm\node_modules -> appveyor.yml'
  - '%APPDATA%\npm-cache -> package.json'
  - '%APPDATA%\npm-cache -> appveyor.yml'

install:
  - ps: Install-Product node $env:nodejs_version
  - node --version
  - npm --version
  - npm ci
  - set KARMA_BROWSERS=IE

before_test:
  - mkdir build
  - npm run-script build

test_script:
  - npm test

build: off
