version: '{build}'

environment:
  nodejs_version: 8

matrix:
  fast_finish: true

cache:
  - node_modules -> package.json
  - '%APPDATA%\npm\node_modules -> appveyor.yml'
  - '%APPDATA%\npm-cache -> package.json'
  - '%APPDATA%\npm-cache -> appveyor.yml'

install:
  - ps: Install-Product node $env:nodejs_version
  - node --version
  - npm --version
  - npm install --global eslint@^4.19.1 write-good@^0.13.1
  - npm install --global karma-cli@^2.0.0
  - npm install
  - npm install --no-save karma-ie-launcher@^1.0.0
  - set KARMA_BROWSERS=IE

before_test:
  - mkdir build
  - npm run-script build

test_script:
  - npm test

build: off
