version: '{build}'

environment:
  nodejs_version: 4

matrix:
  fast_finish: true

install:
  - ps: Install-Product node $env:nodejs_version
  - node --version
  - npm --version
  - npm install --global eslint@^1.8.0 jscs@^2.5.0 write-good@^0.9.1 nsp@^2.0.0
  - npm install --global karma-cli@^0.1.1
  - npm install
  - npm install karma-ie-launcher@^0.2.0
  - set KARMA_BROWSERS=IE

before_test:
  - mkdir build
  - npm run-script build

test_script:
  - npm test

build: off
