version: '{build}'

environment:
  nodejs_version: 0.12

matrix:
  fast_finish: true

install:
  - ps: Install-Product node $env:nodejs_version
  - node --version
  - npm --version
  - npm install
  - npm install karma-ie-launcher@^0.1.5
  - set KARMA_BROWSERS=IE

test_script:
  - npm run-script node-test
  - npm run-script karma-test

build: off
